---
name: Build & Publish container
"on":
  pull_request:

jobs:
  build_and_publish:
    name: Build & Publish to GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Update actions.yml
        uses: mikefarah/yq@v4.30.8
        with:
          cmd: yq e -i '.runs.image = "docker://${{ steps.meta.outputs.tags }}"' action.yml

      - name: Commit Changes to actions.yml
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update actions.yml"
          add: "action.yml"
          default_author: github_actions

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
